#pragma once

#include "parser/query/op/sparql/op_optional.h"
#include "parser/query/op/sparql/op_order_by.h"
#include "parser/query/op/sparql/op_select.h"
#include "parser/query/op/sparql/op_basic_graph_pattern.h"
#include "parser/query/op/sparql/op_triple.h"
#include "parser/query/op/sparql/op_path.h"
#include "parser/query/op/sparql/op_where.h"
#include "parser/query/op/sparql/op_unit_table.h"
#include "parser/query/op/sparql/op_join.h"
#include "parser/query/op/sparql/op_union.h"
#include "parser/query/op/sparql/op_minus.h"
#include "parser/query/op/sparql/op_service.h"
#include "parser/query/op/sparql/op_graph.h"
#include "parser/query/op/sparql/op_filter.h"
